$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
outputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
  model_info_output_path:
    type: uri_folder

jobs:
  prep_data:
    name: data_preparation
    display_name: data-preparation-job
    code: ../../../data-science/src
    command: >-
      python prep.py  
      --raw_data ${{inputs.raw_data}} 
      --train_data ${{outputs.train_data}}
      --test_data ${{outputs.test_data}} 
    environment: azureml:used-cars-train-env@latest
    inputs:
      raw_data: ${{parent.inputs.raw_data}}
    outputs:
      train_data:
        type: uri_folder
      test_data:
        type: uri_folder

  sweep_step:
    # ... (rest of your sweep_step configuration remains the same)
    outputs:
      model_output:
        type: mlflow_model
        path: azureml://datastores/workspaceblobstore/paths/model_output

  register_model:
    name: register_model
    display_name: register-model-job
    code: ../../../data-science/src
    command: >-
      python register.py 
      --model_name ${{inputs.model_name}} 
      --model_path ${{inputs.model_path}} 
      --model_info_output_path ${{outputs.model_info_output_path}}
    environment: azureml:used-cars-train-env@latest
    inputs:
      model_name: "used_cars_price_prediction_model"
      model_path: ${{parent.jobs.sweep_step.outputs.model_output}}
    outputs:
      model_info_output_path:
        type: uri_folder
